const Template = () => (
  <div className="main-template">
    <h1 className="title legal-text-title">PRIVACY POLICY</h1>

    <p>Last updated: June 10, 2023</p>
    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information
      when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and
      use of information in accordance with this Privacy Policy.</p>
    <h2 className="legal-text-subtitle">Interpretation and Definitions</h2>

    <h3 className="legal-text-sec-subtitle indent-on-subtitle">Interpretation</h3>
    <ul>
      <li>The words of which the initial letter is capitalized have meanings defined under the following conditions. The
        following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</li>
    </ul>
    <h3 className="legal-text-sec-subtitle indent-on-subtitle">Definitions</h3>
    <ul>
      <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
      <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a
        party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled
        to vote for election of directors or other managing authority.</li>
      <li><strong>Application</strong> refers to Librum, the software program provided by the Company.</li>
      <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to
        asdasdsa, Kirchenkamp 99, 50226.</li>
      <li><strong>Country</strong> refers to: Nordrhein-Westfalen, Germany</li>
      <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital
        tablet.</li>
      <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
      <li><strong>Service</strong> refers to the Application.</li>
      <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the
        Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to
        provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company
        in analyzing how the Service is used.</li>
      <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or
        from the Service infrastructure itself (for example, the duration of a page visit).</li>
      <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity
        on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>
    <h2 className="legal-text-subtitle">Collecting and Using Your Personal Data</h2>

    <h3 className="legal-text-sec-subtitle indent-on-subtitle">Types of Data Collected</h3>

    <h4>Personal Data</h4>


    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be
      used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <ul className="innerlist">
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Usage Data</li>
      <li>Banking details in case of In-app purchase feature</li>
      <li>All of your existing information on Social Media if you Sign-up through such platforms</li>
    </ul>
    <h4>Usage Data</h4>

    <p>Usage Data is collected automatically when using the Service.</p>
    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type,
      browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those
      pages, unique device identifiers and other diagnostic data.</p>
    <p>When You access the Service by or through a mobile device, We may collect certain information automatically,
      including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of
      Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device
      identifiers and other diagnostic data.</p>
    <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the
      Service by or through a mobile device.</p>

    <h3 className="legal-text-sec-subtitle indent-on-subtitle">Use of Your Personal Data</h3>

    <p>The Company may use Personal Data for the following purposes:</p>
    <ul className="innerlist">
      <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
      <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can
        give You access to different functionalities of the Service that are available to You as a registered user.</li>
      <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the
        products, items or services You have purchased or of any other contract with Us through the Service.</li>
      <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic
        communication, such as a mobile application's push notifications regarding updates or informative communications
        related to the functionalities, products or contracted services, including the security updates, when necessary or
        reasonable for their implementation.</li>
      <li>To provide You with news, special offers and general information about other goods, services, and events which we
        offer that are similar to those that you have already purchased or enquired about unless You have opted not to
        receive such information.</li>
      <li>To manage Your requests: To attend and manage Your requests to Us.</li>
      <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture,
        restructuring, reorganization, dissolution, or other sale or transfer of some or all Our assets, whether as a
        going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us
        about our Service users is among the assets transferred.</li>
      <li>For keeping Reading Statistics of the users: We may gather statistics such as how much they spend reading books, the way the user reads books and similar. We use this data to analyze it and display it to the user in the app. You can always choose to opt-out for this service too.</li>
      <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing, and your experience.</li>
    </ul>
    <p>We may share Your personal information in the following situations:</p>
    <ul className="innerlist">
      <li>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the
        use of our Service, to contact You. It also includes that SSL banking service for safe transactions and to protect
        your banking details.</li>
      <li>For business transfers: We may share or transfer Your personal information in connection with, or during
        negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our
        business to another company.</li>
      <li>With Affiliates: We may share Your information with Our affiliates, in which case we will require those
        affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint
        venture partners or other companies that We control or that are under common control with Us.</li>
      <li>With business partners: We may share Your information with Our business partners to offer You certain products,
        services or promotions.</li>
      <li>With other users: when You share personal information or otherwise interact in the public areas with other
        users, such information may be viewed by all users and may be publicly distributed outside.</li>
      <li>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
    </ul>
    <h3 className="legal-text-sec-subtitle indent-on-subtitle">Retention of Your Personal Data</h3>

    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy
      Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for
      example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our
      legal agreements and policies.</p>
    <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a
      shorter period of time, except when this data is used to strengthen the security or to improve the functionality of
      Our Service, or We are legally obligated to retain this data for longer time Periods.</p>
    <h3 className="legal-text-sec-subtitle indent-on-subtitle">Transfer of Your Personal Data</h3>

    <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places
      where the parties involved in the processing are located. It means that this information may be transferred to — and
      maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where
      the data protection laws may differ than those from Your jurisdiction.</p>
    <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to
      that transfer.</p>
    <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance
      with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country
      unless there are adequate controls in place including the security of Your data and other personal information.</p>
    <h2 className="legal-text-subtitle">Security of Your data</h2>

    <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet,
      or method of electronic storage is 100% secure.</p>
    <p>We have put the necessary security measures in place to guard against accidental loss, unauthorised use or access,
      alteration, or disclosure of your data. Additionally, we only allow employees, agents, contractors, and other third
      parties who have a business need to know access to your data. They have a confidentiality obligation and will only
      act in accordance with our instructions while processing your personal data.</p>
    <p>When we are legally obligated to do so, we will notify you and any relevant regulator of a breach and will have
      procedures in place to deal with any suspected personal data breach.</p>
    <h2 className="legal-text-subtitle">Disclosure of your Data</h2>

    <p>We use several third-party services from Microsoft Corporation, Google LLC, and AWS. We send the data necessary to
      these third-party services to improve the user experience. One example of this is Google’s reCAPTCHA 3, that we use
      to provide simple and straightforward actions on our website and the application, without the need for constant “I’m
      not a computer” puzzles.</p>
    <h2 className="legal-text-subtitle">Delete Your Personal Data</h2>

    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about
      You.</p>
    <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
    <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and
      visiting the account settings section that allows you to manage Your personal information. You may also contact Us to
      request access to, correct, or delete any personal information that You have provided to Us.</p>
    <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis
      to do so.</p>
    <h2 className="legal-text-subtitle">Business Transactions</h2>

    <p>If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will
      provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
    <h2 className="legal-text-subtitle">Law enforcement</h2>

    <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law
      or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
    <h2 className="legal-text-subtitle">Other legal requirements</h2>

    <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
    <ul className="innerlist">
      <li>Comply with a legal obligation</li>
      <li>Protect and defend the rights or property of the Company</li>
      <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
      <li>Protect the personal safety of Users of the Service or the public</li>
      <li>Protect against legal liability</li>
    </ul>
    <h2 className="legal-text-subtitle">Opting Out of the App Service</h2>

    <p>You have the option to opt out of several services that we provide, such as collectingusage data to display statistics, newsletters sent by email, and similar. If the website or application does not provide a way to opt out of optional services we provide, send us an email, and we will assist you.</p>
    <h2 className="legal-text-subtitle">Children's Privacy</h2>

    <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
    <h2 className="legal-text-subtitle">Links to Other Websites</h2>

    <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
    <h2 className="legal-text-subtitle">Changes to this Privacy Policy</h2>

    <p>We may update Our Privacy Policy sometimes. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
    <h2 className="legal-text-subtitle">Contact Us</h2>

    <p>If you have any questions about this Privacy Policy, You can contact us:</p>

    <p>By email: <a href="mailto:help@librumreader.com" target="_blank" rel="noopener noreferrer">help@librumreader.com</a></p>

  </div >
);

export default Template;
